<a href="https://colab.research.google.com/github/gorantlasuhas/git_new/blob/main/dnnlab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

# Define input and output vectors

x1 = np.array([1, 1, 1, 1, 1, 1])
x2 = np.array([-1, -1, -1, -1, -1, -1])
x3 = np.array([1, 1, -1, -1, 1, 1])
x4 = np.array([-1, -1, 1, 1, -1, -1])


y1 = np.array([1, -1, 1])
y2 = np.array([-1, -1, 1])
y3 = np.array([1, -1, -1])
y4 = np.array([1, 1, -1])

# Define weight matrix and initialize to 0
W = np.zeros((6, 3))

# Calculate weights using formula W = summation from 1=0 to 4 of {xi}{yi}^T
#for i in range(4):
    #W += np.outer(x1, y1)

W += 1 * np.outer(x1, y1)
W += 2 * np.outer(x2, y2)
W += 3 * np.outer(x3, y3)
W += 4 * np.outer(x4, y4)

# Print weight matrix for debugging
print("Weight matrix:")
print(W)

# Test the system by giving each input vector and verifying that the output vector is correct
output1 = np.sign(np.dot(x1, W))
print("Output vector for x1:")
print(output1)
print("Expected output vector for x1:")
print(y1)
#assert np.allclose(output1, y1, atol=1e-5)

try:
    assert np.allclose(np.sign(np.dot(x1, W)), y1)
except AssertionError:
    print("Output vector for x1 does not match expected output vector y1")

output2 = np.sign(np.dot(x2, W))
print("Output vector for x2:")
print(output2)
print("Expected output vector for x2:")
print(y2)
#assert np.allclose(output2, y2, atol=1e-5)

try:
    assert np.allclose(np.sign(np.dot(x2, W)), y2)
except AssertionError:
    print("Output vector for x2 does not match expected output vector y2")

output3 = np.sign(np.dot(x3, W))
print("Output vector for x3:")
print(output3)
print("Expected output vector for x3:")
print(y3)
#assert np.allclose(output3, y3, atol=1e-5)

try:
    assert np.allclose(np.sign(np.dot(x3, W)), y3)
except AssertionError:
    print("Output vector for x3 does not match expected output vector y3")

output4 = np.sign(np.dot(x4, W))
print("Output vector for x4:")
print(output4)
print("Expected output vector for x4:")
print(y4)
#assert np.allclose(output4, y4, atol=1e-5)

try:
    assert np.allclose(np.sign(np.dot(x4, W)), y4)
except AssertionError:
    print("Output vector for x4 does not match expected output vector y4")

# Test the aspect of AM where the correct output vector gets produced even if there is some distortion in the input vector
successes = 0
for x, y in zip([x1, x2, x3, x4], [y1, y2, y3, y4]):
    for i in range(6):
        x_distorted = x.copy()
        x_distorted[i] *= -1
        if np.allclose(np.sign(np.dot(x_distorted, W)), y):
            successes += 1
print("-----------------------------------------------------------------------------------------------------------")
print(f"Total number of successes: {successes}")

Weight matrix:
[[ 2. -6.  0.]
 [ 2. -6.  0.]
 [ 4.  8. -2.]
 [ 4.  8. -2.]
 [ 2. -6.  0.]
 [ 2. -6.  0.]]
Output vector for x1:
[ 1. -1. -1.]
Expected output vector for x1:
[ 1 -1  1]
Output vector for x1 does not match expected output vector y1
Output vector for x2:
[-1.  1.  1.]
Expected output vector for x2:
[-1 -1  1]
Output vector for x2 does not match expected output vector y2
Output vector for x3:
[ 0. -1.  1.]
Expected output vector for x3:
[ 1 -1 -1]
Output vector for x3 does not match expected output vector y3
Output vector for x4:
[ 0.  1. -1.]
Expected output vector for x4:
[ 1  1 -1]
Output vector for x4 does not match expected output vector y4
-----------------------------------------------------------------------------------------------------------
Total number of successes: 8


In [10]:
import numpy as np

# Define input and output vectors
x1 = np.array([1, 1, 1, 1, 1, 1])
x2 = np.array([-1, -1, -1, -1, -1, -1])
x3 = np.array([1, 1, -1, -1, 1, 1])
x4 = np.array([-1, -1, 1, 1, -1, -1])
y1 = np.array([1, -1, 1])
y2 = np.array([-1, -1, 1])
y3 = np.array([1, -1, -1])
y4 = np.array([1, 1, -1])

# Define weight matrix and initialize to 0
W = np.zeros((6, 3))

# Calculate weights using formula W = summation from 1=0 to 4 of {xi}{yi}^T
W += np.outer(x1, y1)
W += np.outer(x2, y2)
W += np.outer(x3, y3)
W += np.outer(x4, y4)

# Test the system by giving each input vector and verifying that the output vector is correct
try:
    assert np.allclose(np.dot(x1, W), y1, atol=1e-5)
except AssertionError:
    print("Output vector for x1 does not match expected output vector y1")

try:
    assert np.allclose(np.dot(x2, W), y2, atol=1e-5)
except AssertionError:
    print("Output vector for x2 does not match expected output vector y2")

try:
    assert np.allclose(np.dot(x3, W), y3, atol=1e-5)
except AssertionError:
    print("Output vector for x3 does not match expected output vector y3")

try:
    assert np.allclose(np.dot(x4, W), y4, atol=1e-5)
except AssertionError:
    print("Output vector for x4 does not match expected output vector y4")

# Test the aspect of AM where the correct output vector gets produced even if there is some distortion in the input vector
successes = 0
for x, y in zip([x1, x2, x3, x4], [y1, y2, y3, y4]):
    for i in range(6):
        x_distorted = x.copy()
        x_distorted[i] *= -1
        if np.allclose(np.dot(x_distorted, W), y, atol=1e-5):
            successes += 1

print(f"Total number of successes: {successes}")

Output vector for x1 does not match expected output vector y1
Output vector for x2 does not match expected output vector y2
Output vector for x3 does not match expected output vector y3
Output vector for x4 does not match expected output vector y4
Total number of successes: 0


In [13]:
import numpy as np

# Define input and output vectors
X = [
    np.array([1, 1, 1, 1, 1, 1]),
    np.array([-1, -1, -1, -1, -1, -1]),
    np.array([1, 1, -1, -1, -1, 1]),
    np.array([-1, -1, 1, 1, -1, -1])
]

Y = [
    np.array([1, -1, 1]),
    np.array([-1, -1, 1]),
    np.array([1, -1, -1]),
    np.array([1, 1, -1])
]

# Initialize the weight matrix
W = np.zeros((6, 3))

# Define a learning rate
learning_rate = 0.1

# Train the weight matrix until the output matches the desired output for all input vectors
max_training_iterations = 10000
for iteration in range(max_training_iterations):
    error_count = 0
    for i in range(4):
        output = np.dot(X[i], W)
        if not np.array_equal(np.sign(output), np.sign(Y[i])):
            error = Y[i] - output
            W += learning_rate * np.outer(X[i], error)
            error_count += 1
    if error_count == 0:
        print(f"Training completed in {iteration + 1} iterations.")
        break
print(W)

# Test the AM for each input vector
success_count = 0
print("\nTesting the AM without input distortion:")
for i in range(4):
    output = np.dot(X[i], W)
    if np.array_equal(np.sign(output), np.sign(Y[i])):
        print(f"Input X{i + 1} produces correct output Y{i + 1}")
        success_count += 1
    else:
        print(f"Input X{i + 1} does not produce correct output Y{i + 1}")

print(f"Total successes: {success_count}")

[[ 0.17922133 -0.10795276 -0.09652724]
 [ 0.17922133 -0.10795276 -0.09652724]
 [ 0.34875733  0.31899124 -0.22203124]
 [ 0.34875733  0.31899124 -0.22203124]
 [-0.23517867  0.11444724  0.30507276]
 [ 0.17922133 -0.10795276 -0.09652724]]

Testing the AM without input distortion:
Input X1 does not produce correct output Y1
Input X2 produces correct output Y2
Input X3 produces correct output Y3
Input X4 produces correct output Y4
Total successes: 3


In [14]:

import numpy as np

# Take two sets of patterns:
# Set A: Input Pattern
x1 = np.array([1, 1, 1, 1, 1, 1]).reshape(6, 1)
x2 = np.array([-1, -1, -1, -1, -1, -1]).reshape(6, 1)
x3 = np.array([1, 1, -1, -1, 1, 1]).reshape(6, 1)
x4 = np.array([-1, -1, 1, 1, -1, -1]).reshape(6, 1)

# Set B: Target Pattern
y1 = np.array([1, 1, 1]).reshape(3, 1)
y2 = np.array([-1, -1, -1]).reshape(3, 1)
y3 = np.array([1, -1, 1]).reshape(3, 1)
y4 = np.array([-1, 1, -1]).reshape(3, 1)

# Calculate weight Matrix: W
inputSet = np.concatenate((x1, x2, x3, x4), axis=1)
targetSet = np.concatenate((y1.T, y2.T, y3.T, y4.T), axis=0)
print("\nWeight matrix:")
weight = np.dot(inputSet, targetSet)
print(weight)

# Testing Phase
# Test for Input Patterns: Set A
print("\nTesting for input patterns: Set A")

def testInputs(x, weight):
    # Multiply the input pattern with the weight matrix
    # (weight.T X x)
    y = np.dot(weight.T, x)
    y[y < 0] = -1
    y[y >= 0] = 1
    return np.array(y)

# Initialize a variable to count the total successes
total_successes = 0

for i, pattern in enumerate([x1, x2, x3, x4], start=1):
    print(f"\nOutput of input pattern {i}")
    output = testInputs(pattern, weight)
    print(output)
    if np.array_equal(output, y1 if i == 1 else y2 if i == 2 else y3 if i == 3 else y4):
        print("Success: AM produced the correct output.")
        total_successes += 1
    else:
        print("Failure: AM did not produce the correct output.")

# Test for Distorted Input Patterns: Set A
print("\nTesting for distorted input patterns: Set A")

# Initialize a variable to count the total successes with distorted inputs
total_successes_distorted = 0

for i, pattern in enumerate([x1, x2, x3, x4], start=1):
    print(f"\nTesting distorted input pattern {i}")
    for m in range(6):
        distorted_pattern = np.copy(pattern)
        distorted_pattern[m] *= -1  # Flip the sign of the mth element
        output = testInputs(distorted_pattern, weight)
        if np.array_equal(output, y1 if i == 1 else y2 if i == 2 else y3 if i == 3 else y4):
            total_successes_distorted += 1

print(f"\nTotal successes with undistorted inputs: {total_successes}")
print(f"Total successes with distorted inputs: {total_successes_distorted}")


Weight matrix:
[[4 0 4]
 [4 0 4]
 [0 4 0]
 [0 4 0]
 [4 0 4]
 [4 0 4]]

Testing for input patterns: Set A

Output of input pattern 1
[[1]
 [1]
 [1]]
Success: AM produced the correct output.

Output of input pattern 2
[[-1]
 [-1]
 [-1]]
Success: AM produced the correct output.

Output of input pattern 3
[[ 1]
 [-1]
 [ 1]]
Success: AM produced the correct output.

Output of input pattern 4
[[-1]
 [ 1]
 [-1]]
Success: AM produced the correct output.

Testing for distorted input patterns: Set A

Testing distorted input pattern 1

Testing distorted input pattern 2

Testing distorted input pattern 3

Testing distorted input pattern 4

Total successes with undistorted inputs: 4
Total successes with distorted inputs: 20


In [15]:

import numpy as np

# Define the input and output vectors
X1 = np.array([1, 1, 1, 1, 1, 1])
X2 = np.array([-1, -1, -1, -1, -1, -1])
X3 = np.array([1, 1, -1, -1, 1, 1])
X4 = np.array([-1, -1, 1, 1, -1, -1])

Y1 = np.array([1, -1, 1])
Y2 = np.array([-1, -1, 1])
Y3 = np.array([1, -1, -1])
Y4 = np.array([1, 1, -1])

W = np.zeros((6, 3))

W += 1 * np.outer(X1, Y1)
W += 2 * np.outer(X2, Y2)
W += 3 * np.outer(X3, Y3)
W += 4 * np.outer(X4, Y4)

success_count = 0
total_tests = 0
X = [X1, X2, X3, X4]
Y = [Y1, Y2, Y3, Y4]
print("Weight matrix:")
print(W)

for i in range(len(X)):
    # Test undistorted input
    output = np.sign(np.dot(X[i], W))

    if np.array_equal(output, Y[i]):
        success_count += 1
        print(f"Undistorted input X{i+1}:")
        print("Output:", output)

    for m in range(len(X[i])):
        X_distorted = X[i].copy()
        X_distorted[m] *= -1

        output = np.sign(np.dot(X_distorted, W))

        if np.array_equal(output, Y[i]):
            success_count += 1
            print(f"Distorted input X{i+1} with element {m+1} flipped:")
            print("Distorted Input:", X_distorted)
            print("Output:", output)
        total_tests += 1

print("\nTotal number of successes:", success_count)
print("Total number of tests:", total_tests)

Weight matrix:
[[ 2. -6.  0.]
 [ 2. -6.  0.]
 [ 4.  8. -2.]
 [ 4.  8. -2.]
 [ 2. -6.  0.]
 [ 2. -6.  0.]]
Distorted input X2 with element 1 flipped:
Distorted Input: [ 1 -1 -1 -1 -1 -1]
Output: [-1. -1.  1.]
Distorted input X2 with element 2 flipped:
Distorted Input: [-1  1 -1 -1 -1 -1]
Output: [-1. -1.  1.]
Distorted input X2 with element 5 flipped:
Distorted Input: [-1 -1 -1 -1  1 -1]
Output: [-1. -1.  1.]
Distorted input X2 with element 6 flipped:
Distorted Input: [-1 -1 -1 -1 -1  1]
Output: [-1. -1.  1.]
Distorted input X4 with element 1 flipped:
Distorted Input: [ 1 -1  1  1 -1 -1]
Output: [ 1.  1. -1.]
Distorted input X4 with element 2 flipped:
Distorted Input: [-1  1  1  1 -1 -1]
Output: [ 1.  1. -1.]
Distorted input X4 with element 5 flipped:
Distorted Input: [-1 -1  1  1  1 -1]
Output: [ 1.  1. -1.]
Distorted input X4 with element 6 flipped:
Distorted Input: [-1 -1  1  1 -1  1]
Output: [ 1.  1. -1.]

Total number of successes: 8
Total number of tests: 24
