<a href="https://colab.research.google.com/github/gorantlasuhas/git_new/blob/main/Mllab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

# Read the dataset
data = pd.read_excel('/content/Dry_Bean_Dataset.xlsx')
data.head()

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0  28395    610.291       208.178117       173.888747      1.197191   
1  28734    638.018       200.524796       182.734419      1.097356   
2  29380    624.110       212.826130       175.931143      1.209713   
3  30008    645.884       210.557999       182.516516      1.153638   
4  30140    620.134       201.847882       190.279279      1.060798   

   Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0      0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1      0.411785       29172     191.272750  0.783968  0.984986   0.887034   
2      0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3      0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4      0.333680       30417     195.896503  0.773098  0.990893   0.984877   

   Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  Class  
0     0.913358      0.007332      0.003147      0.834222      0.998724  SEKER  
1     0.953861      0.006979      0.003564      0.909851      0.998430  SEKER  
2     0.908774      0.007244      0.003048      0.825871      0.999066  SEKER  
3     0.928329      0.007017      0.003215      0.861794      0.994199  SEKER  
4     0.970516      0.006697      0.003665      0.941900      0.999166  SEKER

In [4]:
print(data.isnull().sum())

Area               0
Perimeter          0
MajorAxisLength    0
MinorAxisLength    0
AspectRation       0
Eccentricity       0
ConvexArea         0
EquivDiameter      0
Extent             0
Solidity           0
roundness          0
Compactness        0
ShapeFactor1       0
ShapeFactor2       0
ShapeFactor3       0
ShapeFactor4       0
Class              0
dtype: int64


In [35]:
from sklearn.preprocessing import MinMaxScaler

#scaler = MinMaxScaler()
#df_normalized = scaler.fit_transform(data)

scaler = MinMaxScaler()
normalized_data= scaler.fit_transform(data.iloc[:, :-1])
print(normalized_data)


[[0.03405267 0.05857388 0.04426214 ... 0.83304879 0.75099637 0.98061988]
 [0.03550018 0.07755673 0.03047881 ... 0.96731548 0.88498696 0.97497943]
 [0.03825855 0.06803484 0.05263303 ... 0.80094229 0.7361995  0.98719587]
 ...
 [0.09273856 0.16060492 0.17638393 ... 0.42701895 0.4722397  0.9430251 ]
 [0.09277272 0.16365701 0.17970258 ... 0.41532999 0.45691893 0.91334231]
 [0.09282396 0.16944765 0.20088207 ... 0.34689166 0.36476185 0.9701623 ]]


In [31]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.neighbors import NearestNeighbors

i = 1234
j = 7

# Backup the original value for printing
original_value = normalized_data[i, j]

# Find k nearest neighbors
nn = NearestNeighbors(n_neighbors=5)
nn.fit(normalized_data)
distances, indices = nn.kneighbors(normalized_data)
nearest_neighbors = normalized_data[indices[i], :]

# Filter neighbors by the same class as the target sample
target_class = data.iloc[i, -1]
same_class_indices = indices[i][data.iloc[indices[i], -1] == target_class]
same_class_neighbors = normalized_data[same_class_indices, :]

# Calculate simple average
simple_average = np.mean(same_class_neighbors[:, j])

# Calculate weighted average
ep = 1e-5
k_used = min(5, len(same_class_indices))  # Ensure k is not greater than available neighbors
weights = 1.0 / (distances[i, :k_used]+ ep)
weighted_average = np.sum(same_class_neighbors[:, j] * weights) / np.sum(weights)

# Print results
print(f"(i = {i}, j = {j})")
print(f"Original: {original_value:.6f}")
print(f"S_A: {simple_average:.6f}")
print(f"W_A: {weighted_average:.6f}")


(i = 1234, j = 7)
Original: 0.161914
S_A: 0.167892
W_A: 0.161920


In [33]:


for case in range(20):
    # Generate random indices for pretending missing values
    i = np.random.randint(0, normalized_data.shape[0])
    j = np.random.randint(0, normalized_data.shape[1] - 1)

    # Backup the original value for printing
    original_value = normalized_data[i, j]

    nn = NearestNeighbors(n_neighbors=5)
    nn.fit(normalized_data)
    distances, indices = nn.kneighbors(normalized_data)
    nearest_neighbors = normalized_data[indices[i], :]

    # Filter neighbors by the same class as the target sample
    target_class = data.iloc[i, -1]
    same_class_indices = indices[i][data.iloc[indices[i], -1] == target_class]
    same_class_neighbors = normalized_data[same_class_indices, :]

    # Calculate simple average
    simple_average = np.mean(same_class_neighbors[:, j])

    # Calculate weighted average
    ep = 1e-5  # Small value to avoid division by zero
    k_used = min(5, len(same_class_indices))  # Ensure k is not greater than available neighbors
    weights = 1.0 / (distances[i, :k_used] + ep)
    weighted_average = np.sum(same_class_neighbors[:, j] * weights) / np.sum(weights)

    # Print results
    print(f"Case {case + 1}: (i = {i}, j = {j})")
    print(f"Original : {original_value:.6f}")
    print(f"S_A: {simple_average:.6f}")
    print(f"W_A: {weighted_average:.6f}")


Case 1: (i = 10586, j = 8)
Original : 0.710825
S_A: 0.715619
W_A: 0.710833
Case 2: (i = 11165, j = 2)
Original : 0.093913
S_A: 0.093861
W_A: 0.093913
Case 3: (i = 4596, j = 6)
Original : 0.221884
S_A: 0.221713
W_A: 0.221884
Case 4: (i = 5255, j = 11)
Original : 0.260133
S_A: 0.259601
W_A: 0.260133
Case 5: (i = 445, j = 8)
Original : 0.696186
S_A: 0.686325
W_A: 0.696183
Case 6: (i = 12972, j = 6)
Original : 0.068803
S_A: 0.070300
W_A: 0.068804
Case 7: (i = 9070, j = 5)
Original : 0.805299
S_A: 0.812525
W_A: 0.805307
Case 8: (i = 8419, j = 11)
Original : 0.503325
S_A: 0.502553
W_A: 0.503324
Case 9: (i = 8224, j = 13)
Original : 0.346435
S_A: 0.344098
W_A: 0.346432
Case 10: (i = 5006, j = 14)
Original : 0.321097
S_A: 0.321288
W_A: 0.321097
Case 11: (i = 9926, j = 4)
Original : 0.442634
S_A: 0.445571
W_A: 0.442637
Case 12: (i = 6008, j = 0)
Original : 0.123256
S_A: 0.121503
W_A: 0.123255
Case 13: (i = 12925, j = 10)
Original : 0.896975
S_A: 0.896975
W_A: 0.896975
Case 14: (i = 7198, j = 13